controllers:
    resource: ../src/Controller/
    type: attribute
# app_index:
#     path: /
#     # the controller value has the format 'controller_class::method_name'
#     controller: App\Controller\HelloController::index